name: Deploy to Vercel
on: [push, pull_request]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: Borales/actions-yarn@v2.3.0
        with:
          node-version: '14'
      - run: | 
          yarn install
          yarn build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions: 
      deployments: write
    steps: 
      - name: start deployment
        uses: bobheadxi/deployment@v.0.4.3
        id: deployment
        with:   
          step: start
          token: ${{secrets.GITHUB_TOKEN}}
          env: ${{ fromJSON('["Production", "Preview"]')[github.ref != 'refs/heads/main'] }}
      
      - uses: actions/checkout@v2

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: ${{ fromJSON('["--prod", ""]')[github.ref != 'refs/heads/main'] }}
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          scope: ${{secrets.VERCEL_ORG_ID}}
          working-directory: ./
    
      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with: 
          step: finish
          token: ${{secrets.GITHUB_TOKEN}}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id}}
